version: "3.3"

services:
  logstash4:
    hostname: logstash4    
    image: docker.elastic.co/logstash/logstash:7.17.0
    container_name: logstash4
    volumes:
      - type: bind
        source: ./pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash_data/logstash4 
        target: /usr/share/logstash/data
      - type: bind
        source: ./logstash_ssl.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ../cert
        target: /usr/share/logstash/cert
        read_only: true  
      # - type: bind
      #   source: ./cert/logstash/logstash.pkcs8.key
      #   target: /usr/share/logstash/certs/logstash.pkcs8.key
      #   read_only: true    
      # - type: bind
      #   source: ./cert/logstash/logstash.crt
      #   target: /usr/share/logstash/certs/logstash.crt
      #   read_only: true  
      # - type: bind
      #   source: ./cert/logstash/ca.crt
      #   target: /usr/share/logstash/certs/logstash-ca.crt
      #   read_only: true      
    ports:
      - 9606:9600
      - 5048:5044 
      - 5049:5045 
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m    
      LOGSTASH_HOST_NAME: logstash4      