version: '3.3'
services:
    logstash1:
      hostname: logstash1    
      image: docker.elastic.co/logstash/logstash:7.17.0
      container_name: logstash1
      volumes:
        - type: bind
          source: ./pipeline
          target: /usr/share/logstash/pipeline
          read_only: true
        - type: bind
          source: ./data 
          target: /usr/share/logstash/data
        - type: bind
          source: ./logstash.yml
          target: /usr/share/logstash/config/logstash.yml
          read_only: true
      ports:
        - 9600:9600
        - 5044:5044  
      environment:
        LS_JAVA_OPTS: -Xms256m -Xmx256m    

